what_goes_up_when_rain_comes_down = "umbrella"
what_is_full_of_holes_but_holds_water = "sponge"
what_can_you_not_keep_until_you_give_it = "your word"
#print
print(what_goes_up_when_rain_comes_down)
print(what_is_full_of_holes_but_holds_water)
print(what_can_you_not_keep_until_you_give_it)